version: 0.2
phases:
 pre_build:
  commands:
   - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 533267176529.dkr.ecr.me-south-1.amazonaws.com
   - RepoName=web-service
   - REPOSITORY_URI=533267176529.dkr.ecr.me-south-1.amazonaws.com/web-nginx
   - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
   - echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7
   - COMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
   - IMAGE_TAG=${COMIT_HASH:=latest-nginx}
   - ls
 build:
  commands:
   - echo This build on `date`
   - echo building the image ....
   - docker build -t $REPOSITORY_URI:latest-nginx -f ./devops-tools/dockerfile-nginx .
   - docker tag $REPOSITORY_URI:latest-nginx $REPOSITORY_URI:$IMAGE_TAG
 post_build:
  commands:
   - echo completed on `date`
   - echo "Gonna push docker mages"
   - docker push $REPOSITORY_URI:latest-nginx
   - docker push $REPOSITORY_URI:$IMAGE_TAG
   - echo writing image definitions file ...
   - printf '[{"name":"web_nginx","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json