export const colors: Record<string, string> = {
    trigger: ' bg-[#ed2b2b] ',
    message: ' bg-[#2ab9cd] ',
    collect_input: '  bg-[#359cec]',
    list: '  bg-[#359cec]',
    email: ' bg-[#cb62e4] ',
    Condition: ' bg-[#f4c236]',
    calender: ' bg-[#359cec]',
    image: ' bg-[#2ab9cd]',
    carousel: ' bg-[#f5be4f]',
    options1: ' bg-[#f5be4f]',
    dialog: ' bg-[#fc7c29] ',
    button: ' bg-[#f5be4f]',
    slider: ' bg-[#359cec]',
    form: ' bg-[#359cec]',
    file: ' bg-[#359cec]',
    delay: ' bg-[#2ab9cd]',
    flow: ' bg-[#ed2b2b]',
    jump: ' bg-[#2ab9cd]',
    catalogue: ' bg-[#CB62E4]',
    whatsapp_flow: ' bg-[#2ab9cd]',
    dynamic_data: ' bg-[#CB62E4]',
    slack: ' bg-[#fc7c29] ',
    slack_chat: ' bg-[#fc7c29] ',
    set_AI: ' bg-[#fc7c29] ',
    answer_AI: ' bg-[#cb62e4] ',
    zoho: ' bg-[#fc7c29] ',
    zapier: ' bg-[#fc7c29] ',
    freshDesk: ' bg-[#fc7c29] ',
    hubSpot: ' bg-[#fc7c29] ',
    googleSheets: ' bg-[#fc7c29] ',
    salesForece: ' bg-[#fc7c29] ',
    http_request: ' bg-[#cb62e4] ',
    javascript: ' bg-[#cb62e4] ',
    human: 'bg-[#cb62e4]',
    webhook: 'bg-[#cb62e4]' ,
    send_status : ' bg-[#fc7c29] ',
    send_whatsapp : 'bg-[#13be66]' ,
    FlowStart : 'bg-[#ed2b2b]' ,

};

