const appMarketData = [
  {
    href: "/google-analytics",
    title: "Google Analytics",
    description:
      "Track visitor actions in the chatbot flow by firing events to Google Analytics.",
    image: "/app-market/google-analytics-logo.png",
  },
  {
    href: "/service-call",
    title: "HTTP request",
    description:
      "HTTP request initiates a get/post call to other systems using APIs",
    image: "/app-market/service-call-logo.png",
  },
  {
    href: "/webhook",
    title: "Webhook",
    description:
      "Listens to events that occur on this event and proceeds to the next step in the flow.",
    image: "/app-market/webhook-logo.png",
  },
  {
    href: "/streaming",
    title: "HTTP request (Streaming)",
    description:
      "Triggers a method to perform a desired action on your app/system, using a streaming response.",
    image: "/app-market/service-call-logo.png",
  },
  {
    href: "/airtable",
    title: "Airtable",
    description:
      "Fetch data dynamically from your Airtable base and render it as buttons, carousels or image carousels",
    image: "/app-market/airtable-logo.png",
  },
  {
    href: "/calendly",
    title: "Calendly",
    description:
      "Schedule and book appointments using Calendly's interface and continue the conversation flow",
    image: "/app-market/calendly-logo.png",
  },
  {
    href: "/freshdesk",
    title: "Freshdesk",
    description:
      "Creates tickets or fetches the ticket status from your Freshdesk account",
    image: "/app-market/freshdesk-logo.png",
  },
  {
    href: "/google-calendar",
    title: "Google Calendar",
    description:
      "Let’s visitors book meetings with you or your teammates based on the availability shown on your calendar",
    image: "/app-market/google-calendar-logo.png",
  },
  {
    href: "/google-sheets",
    title: "Google Sheets",
    description:
      "Create a new record on your Google Sheets when a new lead/prospect is generated by the chatbot",
    image: "/app-market/google-sheets-logo.png",
  },
  {
    href: "/hubspot",
    title: "HubSpot",
    description:
      "Create a lead on your HubSpot account and map fields with variables",
    image: "/app-market/hubspot-logo.png",
  },
  {
    href: "/salesforce",
    title: "Salesforce",
    description:
      "Create a lead on your Salesforce account and map fields with variables",
    image: "/app-market/salesforce-logo.png",
  },
  {
    href: "/slack",
    title: "Slack",
    description:
      "Get notified and continue conversations on Slack when an important event occurs.",
    image: "/app-market/slack-logo.png",
  },
  {
    href: "/zapier",
    title: "Zapier",
    description:
      'Create "Zaps" within your bot flows to empower your conversational strategy with access to apps available via Zapier',
    image: "/app-market/zapier-logo.png",
  },
  {
    href: "/zoho-crm",
    title: "Zoho CRM",
    description: "Create a lead on your Zoho CRM and map fields with variables",
    image: "/app-market/zoho-logo.png",
  },
];

export default appMarketData;
